[phases.setup]
nixPkgs = ['python311', 'chromium', 'chromedriver', 'pip']

[phases.install]
cmds = [
    'pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[start]
cmd = 'gunicorn src.app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1'