[phases.setup]
nixPkgs = ['python310', 'chromium', 'chromedriver']

[phases.install]
cmds = ['pip install -r requirements.txt']

[start]
cmd = 'gunicorn src.app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1'