[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "gunicorn src.app:app --bind 0.0.0.0:${PORT:-5000} --timeout 120 --workers 1 --log-level info"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10